apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wp-image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp-image
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
